services:
  db_menu_maker:
    image: postgres:latest
    container_name: db_menu_maker
    env_file:
      - ./docker-compose.env
    ports:
      - "5432:5432"
    volumes:
      - volume_menu_maker:/var/lib/db/data
    networks:
      - network_menu_maker
  
  api_menu_maker:
    container_name: api_menu_maker
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "3333:3333"
    depends_on:
      - db_menu_maker
    env_file: .env
    networks:
      - network_menu_maker
  
  pgweb:
    image: sosedoff/pgweb
    restart: always
    container_name: pgweb
    env_file:
      - ./docker-compose.env
    ports:
      - "8081:8081"
    depends_on:
      - db_menu_maker
    networks:
      - network_menu_maker

volumes:
  volume_menu_maker:

networks:
  network_menu_maker:
    driver: bridge